export const FETCH_SCHEME_BEGIN = "FETCH_SCHEME_BEGIN";
export const FETCH_SCHEME_SUCCESS = "FETCH_SCHEME_SUCCESS";
export const FETCH_SCHEME_FAIL = "FETCH_SCHEME_FAIL";
export const SET_CURRENT_SCHEME = "SET_CURRENT_SCHEME";
export const SELECT_ATTR = "SELECT_ATTR";

export const FETCH_REQUESTS_BEGIN = "FETCH_REQUESTS_BEGIN";
export const FETCH_REQUESTS_SUCCESS = "FETCH_REQUESTS_SUCCESS";
export const FETCH_REQUESTS_FAIL = "FETCH_REQUESTS_FAIL";
export const SET_ALL_REQUEST = "SET_ALL_REQUEST";

export const UPDATE_SQUEME_ATTRIBUTE = "UPDATE_SQUEME_ATTRIBUTE";
